### ISSUE TITLE
Download URI reporting possible malicious software?

### ISSUE THREAD

**Issue by jmb322** [EZToolsManuals/EZToolsManuals#57]
In tightly controlled environments, the ability to download from the redirected site is blocked. Is there some reason we are using the mikestammer.com site for downloading these files? There are multiple vendors saying that is a site with malicious software. While I understand that forensic software tools can be viewed as malicious or used maliciously, I believe some other software unrelated to Mr. Zimmerman's tools is affecting the reputation of the site according to my coworkers. Is this a problem for anyone else trying to download the tools? Especially using the PowerShell script... Thanks.

**Comment by EricZimmerman** [comment]
not sure why you posted this here but...

because its my house, and i have 2gb synchronous fiber, and now cloudflare delivers the zip files over their CDN which is way faster, and not costing me significant $$$ when serving from backblaze

your multiple vendors are wrong =)

its a static website, serving files off my host, running via Caddy.

i would love a list of the sites saying mikestamer.com is malicious.

that site is MY site, served via SSL, and all the software is digitally signed, including the powershell script with a trusted certificate.

what other software? what other links? please provide details and i am happy to look into it.

what redirects are you speaking of? why were you ok with it coming from backblaze for years but now mikestammer is an issue?

again, the vendors, and your coworkers are incorrect here. treat that as FUD unless you can provide actual proof of something malicious.

**Comment by EricZimmerman** [comment]
i can certainly have stuff hosted from https://download.ericzimmermanstools.com if you would find that more palatable?

**Comment by EricZimmerman** [comment]
i should also note, you only need to worry about the redirection ONCE, when converting from the OLD script, to the new. if you want, redownload the current script from my site and it has the "normal" links in it. i had to do it the way I did so people would not be forced to download the ps1 again (which would be an INSANE amount of people)

**Comment by EricZimmerman** [comment]
ill give this another day or 2 for replies, then close if i dont hear anything back from @jmb322

**Comment by jmb322** [comment]
Eric,
Good to know. Sorry for the delay - just saw this. I will ask our techs for the sites where we saw the reports so I can get them to you. Since this is your personal site/page/server, there shouldn't be a problem. My guess is that when the Forensic tools are seen that some of them may be identified incorrectly as malicious. I've seen that a lot over the years. Thanks for the update. I wasn't sure where it would be best to post. Sorry if this was not a good place. I certainly didn't intend to create unnecessary alarm, but now that I think about it, I may have inadvertently done so. I apologize. Thank you for your love of and dedication to the profession! I know you are and have been regarded as an excellent authority in this world and your work on the tools and on KAPE is well respected. Thank you for it! jmb

**Comment by EricZimmerman** [comment]
its all good. just want to make sure you have what you need to get the tools.

ill close this for now, but feel free to post any additional details here when you get them.

thanks again
